### ISSUE TITLE
Is there a available pkl model？

### ISSUE THREAD

**Issue by wadesunyang** [liruilong940607/Pose2Seg#1]
hollo, thanks for your job, is there a available pkl model to test the myself picture?

**Comment by liruilong940607** [comment]
I was on a vacation, sorry for the delay.

I retrained our model using this repo and got similar results with our paper. You can download the final weights [here](https://drive.google.com/file/d/193i8b40MJFxawcJoNLq1sG0vhAeLoVJG/view?usp=sharing).
