### ISSUE TITLE
代码结果可视化问题

### ISSUE THREAD

**Issue by douxiao** [liruilong940607/Pose2Seg#10]
您好 ，我按下面这种方法生成json文件 然后可视化时出现错误。
代码如下：
imgIds.append(image_id)
filename = "./seg_images/annotations/" + "instances_val2017.json"
f_obj = open(filename, 'w')
json.dump(results_segm, f_obj)
这样生成json文件后，json部分显示如下：
[{"category_id": 1, "segmentation": {"counts": "hX]52V=3N1O1O1O100O2N1O1O1O1O1iNC^E?_:I[E9d:IVE<i:GQE=n:EmD?S;l001N3N3N3L2N2OO10O1001O1l0UO<D7H3MO0O2N2N1O101N3M4L5K7I5K5J7J4L4K7VOgDeN86W;f0S1DQmV2", "size": [426, 640]}, "image_id": 139, "score": 1.0}, {"category_id": 1, "segmentation": {"counts": "cQf31U=5K5L3N2N2O1N2O0O2OO10O10000O010000O010O010O010O01O00100O0010O010O10O10O010O0100O010O10OO2O001O1O010O1O1N1O2O1O001M3M2O2O1L3K6L4M3N1N3iNSNoFP2n8[NgFg1W9bNaF`1Z9Z1L4N101O1eIdLh2\3SMmLh2V3SMQMi2P3TMUMi2l2VMVMh2k2VMYMh2g2VM]Mg2d2VMbMg2^2XMfMe2[2XMiMe2X2ZMlMc2U2

但是我看您生成的 ochuman.json文件内容显示 不是这样的 ，我不知道 哪里出了问题。
我现在想生成json文件，然后可视化。
期待您的回复，谢谢！

**Comment by douxiao** [comment]
是保存时，格式出问题了吗? 应该怎样控制一下格式，还是哪里问题？
还有 最后 ：数据我只用了 cocoVal
    print('===========>   testing    <===========')
    if args.coco:
        test(model, dataset='cocoVal')
   # if args.OCHuman:
   #    test(model, dataset='OCHumanVal')
   #    test(model, dataset='OCHumanTest')

**Comment by douxiao** [comment]
是保存时，格式出问题了吗? 应该怎样控制一下格式，还是哪里问题？
还有 最后 ：数据我只用了 cocoVal
print('===========> testing <===========')
if args.coco:
    test(model, dataset='cocoVal')

**Comment by douxiao** [comment]
是保存时，格式出问题了吗? 应该怎样控制一下格式，还是哪里问题？
还有 最后 ：数据我只用了 cocoVal
print('===========> testing <===========')
if args.coco:
    test(model, dataset='cocoVal')

**Comment by liruilong940607** [comment]
"instances_val2017.json" 是COCO的格式，请参考COCO的可视化方式[[link](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI)]。（与"ochuman.json"的格式是不同的）

**Comment by douxiao** [comment]
非常感谢回复， 我那样保存json文件 对吗？

**Comment by douxiao** [comment]
我就是 使用的cocoapi 但是 加载json文件的时候报错了。

**Comment by liruilong940607** [comment]
保存的方式是对的，但是我猜你用cocoapi load的方式不对。
注意保存好的json是coco预测结果的格式，不是coco annotation的格式。所以应该这样load：
```
cocoGt=COCO(annFile)
cocoDt=cocoGt.loadRes(resFile)
```
其中cocoDt是你需要的。
参见：https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb

**Comment by douxiao** [comment]
好的，非常感谢！
