### ISSUE TITLE
关于输入的问题

### ISSUE THREAD

**Issue by lingtengqiu** [liruilong940607/Pose2Seg#3]
最近在follow 你的工作，你们的输入是单张图片然后估计skeleton 在进行affine，还是输入是两个，一个是图片另外一个是已经存在的skeleton？ 我对论文又些许不明白

**Comment by liruilong940607** [comment]
我们的工作输入是image + human pose。 我们用了其他的方法来从图片中提取human pose然后作为我们方法的输入。具体请参考论文

**Comment by lingtengqiu** [comment]
那这里有个问题，你们用什么方法来提取pose，也是先detect 的方法做为输入码，我比较愚昧，我看论文时直接将image和pose 做为输入了，我有点不太清楚pose哪里来的。

**Comment by liruilong940607** [comment]
我们用了这个方法提取pose，见论文Sec5.1 & Sec5.2：
[26] Associative embedding: End-to-end learning for joint detection and grouping.

这是一个不依赖于detection的自底向上的方法。在论文Introduction中我们有对自底向上的方法做了一个简介：“The main idea of the bottom-up methods is to first detect keypoints for each body part for all the people, and then group or connect those parts to form several instances of human pose, which makes it possible to seperate two in- tertwined human instances with a large overlap.”

**Comment by lingtengqiu** [comment]
请问有Associative embedding: End-to-end learning for joint detection and grouping 的源码吗，我想参考下它的tag的做法

**Comment by hih70** [comment]
> 
> 
> 请问有Associative embedding: End-to-end learning for joint detection and grouping 的源码吗，我想参考下它的tag的做法

I think you can find the code for Associative embedding here below
https://github.com/princeton-vl/pose-ae-train

**Comment by lxtGH** [comment]
所以test的pose 输入也是Associative Embedding???

**Comment by lxtGH** [comment]
好像没有发现在test上面的结果？对于human这个类的ap.....
