### ISSUE TITLE
What's the environment setup and requirement?

### ISSUE THREAD

**Issue by jasam-sheja** [liruilong940607/Pose2Seg#31]
Your work is fascinating.

Could you share some information on the environment you used, like OS (& version), python version, and libraries' versions (especially PyTorch)?

Also, when it comes to inference, How much GPU memory is required for a single image (let's say 512x512, same as your experiments)?

Thanks

**Comment by KainingYing** [comment]
the library version can see in the ./requirements.txt,and I set batchsize=4 on my 1080Ti for training.
