### ISSUE TITLE
结果可视化

### ISSUE THREAD

**Issue by GittersYang** [liruilong940607/Pose2Seg#8]
您好
我运行了你的模型在ochuamn上  给了一些数  
请问 怎么将结果可视化出来呢 好像在你们的论文里图片那样

**Comment by liruilong940607** [comment]
我们的code里没有提供直接可视化的代码。

你可以在`test.py` Line47 加上一行代码将预测结果`results_segm`保存为json文件，再用[cocoapi](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoDemo.ipynb)中的方式可视化结果。（我们生成的结果与coco的格式是一致的）

**Comment by douxiao** [comment]
您好 ，我按这种方法可视化。代码如下：
        imgIds.append(image_id)
        filename = "./seg_images/annotations/" + "instances_val2017.json"
        f_obj = open(filename, 'w')
        json.dump(results_segm, f_obj)
这样生成json文件后，json部分显示如下：
[{"category_id": 1, "segmentation": {"counts": "hX]52V=3N1O1O1O100O2N1O1O1O1O1iNC^E?_:I[E9d:IVE<i:GQE=n:EmD?S;l001N3N3N3L2N2OO10O1001O1l0UO<D7H3MO0O2N2N1O101N3M4L5K7I5K5J7J4L4K7VOgDeN86W;f0S1DQmV2", "size": [426, 640]}, "image_id": 139, "score": 1.0}, {"category_id": 1, "segmentation": {"counts": "cQf31U=5K5L3N2N2O1N2O0O2OO10O10000O010000O010O010O010O01O00100O0010O010O10O10O010O0100O010O10OO2O001O1O010O1O1N1O2O1O001M3M2O2O1L3K6L4M3N1N3iNSNoFP2n8[NgFg1W9bNaF`1Z9Z1L4N101O1eIdLh2\\3SMmLh2V3SMQMi2P3TMUMi2l2VMVMh2k2VMYMh2g2VM]Mg2d2VMbMg2^2XMfMe2[2XMiMe2X2ZMlMc2U2

但是我看您生成的 ochuman.json文件内容显示 不是这样的 ，我不知道 哪里出了问题。我现在想生成json文件，然后可视化。

**Comment by manansaxena** [comment]
> 您好 ，我按这种方法可视化。代码如下：
> imgIds.append(image_id)
> filename = "./seg_images/annotations/" + "instances_val2017.json"
> f_obj = open(filename, 'w')
> json.dump(results_segm, f_obj)
> 这样生成json文件后，json部分显示如下：
> [{"category_id": 1, "segmentation": {"counts": "hX]52V=3N1O1O1O100O2N1O1O1O1O1iNC^E?_:I[E9d:IVE<i:GQE=n:EmD?S;l001N3N3N3L2N2OO10O1001O1l0UO<D7H3MO0O2N2N1O101N3M4L5K7I5K5J7J4L4K7VOgDeN86W;f0S1DQmV2", "size": [426, 640]}, "image_id": 139, "score": 1.0}, {"category_id": 1, "segmentation": {"counts": "cQf31U=5K5L3N2N2O1N2O0O2OO10O10000O010000O010O010O010O01O00100O0010O010O10O10O010O0100O010O10OO2O001O1O010O1O1N1O2O1O001M3M2O2O1L3K6L4M3N1N3iNSNoFP2n8[NgFg1W9bNaF`1Z9Z1L4N101O1eIdLh2\3SMmLh2V3SMQMi2P3TMUMi2l2VMVMh2k2VMYMh2g2VM]Mg2d2VMbMg2^2XMfMe2[2XMiMe2X2ZMlMc2U2
> 
> 但是我看您生成的 ochuman.json文件内容显示 不是这样的 ，我不知道 哪里出了问题。我现在想生成json文件，然后可视化。

Were you able to solve this ?
